# Generated by Django 4.0.2 on 2022-02-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heart_rate', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
