# Generated by Django 4.0.2 on 2022-02-14 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heart_rate', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_clinician', models.BooleanField(default=False)),
                ('is_patient', models.BooleanField(default=False)),
                ('patient_ids', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_patient_ids', to=settings.AUTH_USER_MODEL)),
                ('patient_measurements', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient_measurements.patientmeasurement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
