# Generated by Django 4.0.2 on 2022-02-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_measurements', '0002_patientmeasurement_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmeasurement',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
